# Generated by Django 4.2.6 on 2025-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gulf_central", "0017_enquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("blog_name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
